version: "2.4"

services:
  app:
    build:
      context: .
      dockerfile: .
    container_name: go_app
    # restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    # network_mode: host