// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	api "github.com/wmaldonadoc/academy-go-q42021/infrastructure/api"

	model "github.com/wmaldonadoc/academy-go-q42021/domain/model"
)

// PokemonPresenter is an autogenerated mock type for the PokemonPresenter type
type PokemonPresenter struct {
	mock.Mock
}

// ResponseMappedPokemonFromAPI provides a mock function with given fields: p
func (_m *PokemonPresenter) ResponseMappedPokemonFromAPI(p *api.APIResponse) *model.Pokemon {
	ret := _m.Called(p)

	var r0 *model.Pokemon
	if rf, ok := ret.Get(0).(func(*api.APIResponse) *model.Pokemon); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pokemon)
		}
	}

	return r0
}

// ResponsePokemon provides a mock function with given fields: p
func (_m *PokemonPresenter) ResponsePokemon(p *model.Pokemon) *model.Pokemon {
	ret := _m.Called(p)

	var r0 *model.Pokemon
	if rf, ok := ret.Get(0).(func(*model.Pokemon) *model.Pokemon); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pokemon)
		}
	}

	return r0
}
