// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	api "github.com/wmaldonadoc/academy-go-q42021/infrastructure/api"

	pokerrors "github.com/wmaldonadoc/academy-go-q42021/pokerrors"
)

// HTTPClient is an autogenerated mock type for the HTTPClient type
type HTTPClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: url
func (_m *HTTPClient) Get(url string) (*api.APIResponse, *pokerrors.APIClientError) {
	ret := _m.Called(url)

	var r0 *api.APIResponse
	if rf, ok := ret.Get(0).(func(string) *api.APIResponse); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.APIResponse)
		}
	}

	var r1 *pokerrors.APIClientError
	if rf, ok := ret.Get(1).(func(string) *pokerrors.APIClientError); ok {
		r1 = rf(url)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pokerrors.APIClientError)
		}
	}

	return r0, r1
}
