// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	workers "github.com/wmaldonadoc/academy-go-q42021/workers"
	pool "github.com/wmaldonadoc/academy-go-q42021/workers/pool"
)

// Dispatcher is an autogenerated mock type for the Dispatcher type
type Dispatcher struct {
	mock.Mock
}

// SetPoolSize provides a mock function with given fields: num, itemsPerWorker, disc
func (_m *Dispatcher) SetPoolSize(num int, itemsPerWorker int, disc string) *workers.Disp {
	ret := _m.Called(num, itemsPerWorker, disc)

	var r0 *workers.Disp
	if rf, ok := ret.Get(0).(func(int, int, string) *workers.Disp); ok {
		r0 = rf(num, itemsPerWorker, disc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workers.Disp)
		}
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *Dispatcher) Start() *workers.Disp {
	ret := _m.Called()

	var r0 *workers.Disp
	if rf, ok := ret.Get(0).(func() *workers.Disp); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workers.Disp)
		}
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *Dispatcher) Stop() {
	_m.Called()
}

// Submit provides a mock function with given fields: job
func (_m *Dispatcher) Submit(job pool.Job) {
	_m.Called(job)
}
