// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	controller "github.com/wmaldonadoc/academy-go-q42021/interface/controller"
)

// Registry is an autogenerated mock type for the Registry type
type Registry struct {
	mock.Mock
}

// NewAppController provides a mock function with given fields:
func (_m *Registry) NewAppController() controller.AppController {
	ret := _m.Called()

	var r0 controller.AppController
	if rf, ok := ret.Get(0).(func() controller.AppController); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(controller.AppController)
	}

	return r0
}
